language: java
services:
  - docker
env:
  - DOCKER_USER=leopppp
  - DOCKER_PASS=pzlvxq710103
before_script:
  - echo $LAST_COMMIT_SHA 
jobs:
  include:
    - stage: test 
      script: 
      - mvn clean test
    - stage: build
      skipclean: true
      script: 
      - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - docker build -t java-rest-template:1.0 --build-arg LAST_COMMIT_SHA=$(git rev-parse HEAD) .
    - stage: publish
      skipclean: true
      script:
      - docker images 
      - docker tag java-rest-template:1.0 leopppp/java-rest-template:1.0
      - docker push leopppp/java-rest-template:1.0
