language: java
services:
  - docker
jobs:
  include:
    - stage: test
    before_script:
    - echo ${TRAVIS_COMMIT} > lastcommitsha
    - cat lastcommitsha
    script: mvn clean install
    - stage: build
      script: mvn clean install
    - stage: publish
      script: mvn clean install