language: java
services:
  - docker
jobs:
  include:
    - stage: test
      script: mvn clean install
    - stage: build
      script: mvn clean install
    - stage: publish
      script: mvn clean install