language: java
services:
  - docker
env:
  - LAST_COMMIT_SHA=${TRAVIS_COMMIT}
jobs:
  include:
    - stage: test
      before-script: echo $LAST_COMMIT_SHA
      script: mvn clean install
    - stage: build
      script: mvn clean install
    - stage: publish
      script: mvn clean install